export const colors = {
  primaryDarkBlue: '#032E46',
  secondaryGreen: '#6EAD7C',
  offWhite: '#F8F7F4',
  figmaPageBackground: '#F6F4ED',
  figmaLightGray: '#D9D9D9',
  figmaLightBlue: '#DAEDF0',
  figmaPlaceholderText: '#999999',
  sidebarGray: '#E9ECEF',
  headerBlueGray: '#DDE2E7',
  loginCardBg: '#F3F7F2',
  primaryText: '#333333',
  secondaryText: '#6C757D',
  border: '#CED4DA',
  loginCardBorder: '#D2E0D1',
  badgeExemplary: '#6EAD7C',
  badgeFoundational: '#D9534F',
  badgeAdvanced: '#5BC0DE',
  badgeProficient: '#F0AD4E'
};
