-- Migration for branching survey schema
CREATE TABLE IF NOT EXISTS Survey (
  id TEXT PRIMARY KEY NOT NULL,
  objective TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deployedAt DATETIME,
  analysisResultText TEXT
);

CREATE TABLE IF NOT EXISTS Node (
  id TEXT PRIMARY KEY NOT NULL,
  surveyId TEXT NOT NULL,
  type TEXT NOT NULL,
  content TEXT NOT NULL,
  sentimentScore REAL,
  sentimentSummary TEXT,
  FOREIGN KEY (surveyId) REFERENCES Survey(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Edge (
  id TEXT PRIMARY KEY NOT NULL,
  surveyId TEXT NOT NULL,
  sourceNodeId TEXT NOT NULL,
  targetNodeId TEXT NOT NULL,
  conditionValue TEXT,
  FOREIGN KEY (surveyId) REFERENCES Survey(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (sourceNodeId) REFERENCES Node(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (targetNodeId) REFERENCES Node(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Response (
  id TEXT PRIMARY KEY NOT NULL,
  nodeId TEXT NOT NULL,
  answer TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (nodeId) REFERENCES Node(id) ON DELETE CASCADE ON UPDATE CASCADE
);
